apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobbr-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobbr
  template:
    metadata:
      labels:
        app: dobbr
    spec:
      containers:
        - name: dobbr-container
          image: samisundar/dobbr:latest
          ports:
            - containerPort: 80

---------------------

apiVersion: v1
kind: Service
metadata:
  name: dobbr-service
spec:
  type: NodePort
  selector:
    app: dobbr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007


